config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  resources :retailers
  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
	has_and_belongs_to_many :retailers

	validates :product_name, :brand_name, presence: true
	validates :retail_price, numericality: true
end

app/models/products_retailer.rb
class ProductsRetailer < ApplicationRecord
  belongs_to :product
  belongs_to :retailer
end

app/models/retailer.rb
class Retailer < ApplicationRecord
	has_and_belongs_to_many :products
	has_one_attached :qr_code
	validates :name, presence: { message: "Please enter a name" }
	validates :maps_url, presence: { message: "Please select a valid address from the dropdown" }
  
	
	after_save :generate_qr, if: :saved_change_to_maps_url?

  def generate_qr
		# get maps_url (google maps url generated based on retailer address)
		url = self.maps_url
    
		# generate a qr code for url
		qrcode = RQRCode::QRCode.new(url)

		# convert qr code to png
		# stored as ChunkyPNG::Image instance
		# 	(see https://github.com/wvanbergen/chunky_png)
		png = qrcode.as_png(
			bit_depth: 1,
			border_modules: 4,
			color_mode: ChunkyPNG::COLOR_GRAYSCALE,
			color: "black",
			file: nil,
			fill: "white",
			module_px_size: 6,
			resize_exactly_to: false,
			resize_gte_to: false,
			size: 240
		)

		# returns a saved blob instance
		blob = ActiveStorage::Blob.create_after_upload!(
			# create in-memory file-like object
			# file needs to be created and "stored" prior to upload
      io: StringIO.new(png.to_s),
      filename: "retailer-#{self.id}-qr",
      content_type: 'image/png' # specifies MIME type
    )

		# attach active_storage blob to retailer record
		self.qr_code.attach(blob)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:brand_name, :product_name, :product_code, :retail_price, retailer_ids: [])
    end
end

app/controllers/retailers_controller.rb
class RetailersController < ApplicationController
  before_action :set_retailer, only: %i[ show edit update destroy ]

  # GET /retailers or /retailers.json
  def index
    @retailers = Retailer.all
  end

  # GET /retailers/1 or /retailers/1.json
  def show
  end

  # GET /retailers/new
  def new
    @retailer = Retailer.new
  end

  # GET /retailers/1/edit
  def edit
  end

  # POST /retailers or /retailers.json
  def create
    @retailer = Retailer.new(retailer_params)

    respond_to do |format|
      if @retailer.save
        format.html { redirect_to retailer_url(@retailer), notice: "Retailer was successfully created." }
        format.json { render :show, status: :created, location: @retailer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @retailer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /retailers/1 or /retailers/1.json
  def update
    respond_to do |format|
      if @retailer.update(retailer_params)
        format.html { redirect_to retailer_url(@retailer), notice: "Retailer was successfully updated." }
        format.json { render :show, status: :ok, location: @retailer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @retailer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /retailers/1 or /retailers/1.json
  def destroy
    @retailer.destroy

    respond_to do |format|
      format.html { redirect_to retailers_url, notice: "Retailer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_retailer
      @retailer = Retailer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def retailer_params
      params.require(:retailer).permit(:name, :address, :maps_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/retailers_helper.rb
module RetailersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CamerasRUs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.credentials.google[:maps] %>&libraries=places&callback=initMap" async defer data-turbolinks-eval="false"></script>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :brand_name %>
    <%= form.text_field :brand_name %>
  </div>

  <div class="field">
    <%= form.label :product_name %>
    <%= form.text_field :product_name %>
  </div>

  <div class="field">
    <%= form.label :product_code %>
    <%= form.text_field :product_code %>
  </div>

  <div class="field">
    <%= form.label :retail_price %>
    <%= form.text_field :retail_price %>
  </div>

  <div class="field">
    <h4>Retailers who stock this product:</h4>

    <% if Retailer.all.empty? %>
      <p>There are currently no retailers in the database</p>
    <% end %>
    
    <%= form.collection_check_boxes :retailer_ids, Retailer.all, :id, :name do |retailer| %>
      <div class="collection-check-box">
        <%= retailer.check_box %>
        <%= retailer.label class: "checkbox-label" %>
      </div>
    <% end %>
    
    <br>
    
    <%= link_to "Add a new retailer", new_retailer_path, target: "_blank" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Brand</th>
      <th>Product code</th>
      <th>Retail price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.product_name, product %></td>
        <td><%= product.brand_name %></td>
        <td><%= product.product_code %></td>
        <td><%= number_to_currency(product.retail_price) %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @product.product_name %></h1>

<p>
  <strong>Brand:</strong>
  <%= @product.brand_name %>
</p>

<p>
  <strong>Product code:</strong>
  <%= @product.product_code %>
</p>

<p>
  <strong>Retail price:</strong>
  <%= number_to_currency(@product.retail_price) %>
</p>

<h3>Retailer Locations</h3>
<% if @product.retailers.empty? %>
  <p><strong><em>Product not currently available at any locations</em></strong></p>
<% else %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @product.retailers.each do |retailer| %>
        <tr>
          <td><%= link_to retailer.name, retailer %></td>
          <td><%= link_to retailer.address, retailer.maps_url, target: "_blank" %></td>
          <td><%= image_tag retailer.qr_code if retailer.qr_code.attached? %></td>
          <td><%= link_to 'Show', retailer %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/retailers/_form.html.erb
<%= form_with(model: retailer) do |form| %>
  <% if retailer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(retailer.errors.count, "error") %> prohibited this retailer from being saved:</h2>

      <% retailer.errors.values.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field" data-controller="address" data-action="map-loaded@window->address#initGoogle">
    <%= form.label :address %>
    <%= form.search_field :address, size: "50x10", "data-address-target" => "input", "data-action" => "change->address#addressChanged" %>
    <%= form.hidden_field :maps_url, name: "retailer[maps_url]", "data-address-target" => "url" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/retailers/edit.html.erb
<h1>Editing Retailer</h1>

<%= render 'form', retailer: @retailer %>

<%= link_to 'Show', @retailer %> |
<%= link_to 'Back', retailers_path %>

app/views/retailers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Retailers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @retailers.each do |retailer| %>
      <tr>
        <td><%= link_to retailer.name, retailer %></td>
        <td><%= link_to retailer.address, retailer.maps_url, target: "_blank" %></td>
        <td><%= link_to 'Show', retailer %></td>
        <td><%= link_to 'Edit', edit_retailer_path(retailer) %></td>
        <td><%= link_to 'Destroy', retailer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/retailers/new.html.erb
<h1>New Retailer</h1>

<%= render 'form', retailer: @retailer %>

<%= link_to 'Back', retailers_path %>

app/views/retailers/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @retailer.name %></h1>

<p>
  <%= link_to @retailer.address, @retailer.maps_url, target: "_blank" %>
</p>

<h4>Scan QR code for Google Maps link</h4>
<p>
  <%= image_tag @retailer.qr_code if @retailer.qr_code.attached? %>
</p>

<%= link_to 'Edit', edit_retailer_path(@retailer) %> |
<%= link_to 'Back', retailers_path %>

app/views/shared/_navbar.html.erb
<nav id="navbar">
	<span class="four columns">
		<%= link_to_unless_current 'Home', root_path %>
		<%= link_to_unless_current 'Products', products_path %>
		<%= link_to_unless_current 'Retailers', retailers_path %>
	</span>

	<span class="eight columns">
		<%= link_to 'Add a new product', new_product_path, class: "button button-primary" %>
		<%= link_to 'Add a new retailer', new_retailer_path, class: "button button-primary" %>
	</span>
</nav>